### ISSUE TITLE
Add Generic Error Component

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/aletheia#100]
Add a generic error component.

# Todo

- [x] Design / UI / UX definitions
- [ ] Define which kinds of errors should be handled
   - `4xx` - Client side errors (should be covered by validations)
   - `5xx` - Server side errors
   - Connection errors (UI-Renderer only - depending on browser support, fallback polling)
- [ ] Define Error Component schema
   - Error Message
   - contact data - generic and optional specific

**Comment by AndyOGo** [comment]
What about translations and connectivity checks?

**Comment by AndyOGo** [comment]
@mjenny 
@lina-salih 
Connectivity checks are rather complex:
https://www.html5rocks.com/en/mobile/workingoffthegrid/
