### ISSUE TITLE
Automatic documentation generation to markdown is not complete

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/aletheia#153]
Unfortunately `@adobe/jsonschema2md` isn't feature complete and comes with at least following limitations:

- [ ] [`default` values not supported](https://github.com/adobe/jsonschema2md/issues/68) [PR here](https://github.com/adobe/jsonschema2md/pull/71)
- [ ] [`enum`s are broken in nested schemas](https://github.com/adobe/jsonschema2md/issues/69) [PR here](https://github.com/adobe/jsonschema2md/pull/70)
- [ ] [refs in items of type array do not work](https://github.com/adobe/jsonschema2md/issues/72)
- [ ] [`allOf`, `anyOf`, `oneOf` etc. do not work](https://github.com/adobe/jsonschema2md/issues/52)
- [ ] [real blocker bug](https://github.com/adobe/jsonschema2md/issues/73) - only supporting `properties` at root level of schema (no other types...)

Actually here are [all issues](https://github.com/adobe/jsonschema2md/issues)...

**Comment by TheDadi** [comment]
what about https://github.com/AnalyticalGraphicsInc/wetzel

**Comment by AndyOGo** [comment]
Well I saw that too, but it:
- seems to not on npm ??? https://github.com/AnalyticalGraphicsInc/wetzel#getting-started
- has limitations too https://github.com/AnalyticalGraphicsInc/wetzel#Limitations

Actually the same is true for `@adobe/jsonschema2md`, so I will give it a try.

**Comment by AndyOGo** [comment]
Okay `wetzel` is on npm despite the confussing getting started description...
https://www.npmjs.com/package/wetzel

**Comment by AndyOGo** [comment]
And it has not `bin` flag in it's package.json, so:

```sh
> wetzel schemas/api-schema.json -a

sh: wetzel: command not found
```
